[package]
name = "cfg"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.32"
petgraph = "0.6.4"
rust-sugiyama = { git = "https://github.com/paddison/rust-sugiyama.git" }

[dev-dependencies]
eframe = "0.32"
